databases:
  - name: ruby_exam_app_production
    databaseName: ruby_exam_app_production
    plan: free

services:
  - type: web
    plan: free
    name: ruby_exam_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby_exam_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2